name: Run Python Script

on:
  workflow_dispatch:

  schedule:
    - cron: '1 16 * * *' # 这是你原来的时间
    - cron: '0 21 * * *' # 每天的21:00
    - cron: '0 4 * * *'  # 每天的04:00
    - cron: '0 12 * * *' # 每天的12:00

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install requests pytz beautifulsoup4

    - name: Run Python Script
      run: |
        if [[ "$(date +'%H')" == "16" ]]; then
          python dm/更新.py
          python dm/pc.py
        elif [[ "$(date +'%H')" == "21" || "$(date +'%H')" == "04" || "$(date +'%H')" == "12" ]]; then
          python dm/pc.py
        fi

    - name: Move generated HTML
      run: |
        mv zy.html dm/
        mv output.html dm/

    - name: commit
      run: |
        git config --global user.email 827737456@qq.com
        git config --global user.name lenfeng666
        git add .
        git commit -m "update" -a
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}